name: docker

on:
  release:
    types: [published]
  watch:
    types: [started]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: tag env
      run: echo ::set-env name=RELEASE_VERSION::$(echo {GITHUB_REF#ref/*/})
    - name: docker build & push
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: coolexplorer/kube-consul-registrator
        tag: $RELEASE_VERSION
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
