name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test kube-consul-registrator.Tests/kube-consul-registrator.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./kube-consul-registrator.Tests/coverage.opencover.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
